# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ICRG @ Shanghai Jiao Tong University
title_abbr: ICRG@SJTU
email: zhezhi.he@sjtu.edu.cn
description: > # this means to ignore newlines until "baseurl:" Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
    Advanced Computing Research Group at Shanghai Jiao Tong University
baseurl: ""
url: "" # config for jekyll-sitemap

institution: Shanghai Jiao Tong University
department: Department of Computer Science and Engineering



include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

# jekyii-scholar
scholar:
  last_name: He
  first_name: Zhezhi

  style: _bibliography/my_ieee.cls
  locale: en

  source: ./_bibliography
  bibliography: references.bib

  group_by: year
  group_order: descending

  replace_strings: true
  join_strings: true

  bibliography_template: bibliography

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*" 

  type_order: [article, inproceedings]

  
# Plugins
plugins:
  - jemoji
  # - jekyll-sitemap
