# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Intelligent Computing Research Group 
title_abbr: ICRG@SJTU
email: zhezhi.he@sjtu.edu.cn
description: >
    Intelligent Computing Research Group at Shanghai Jiao Tong University, led by Prof. Zhezhi He, researches brain-inspired algorithms, AI infrastructure, computer architecture, circuits, and emerging devices.
baseurl: ""
url: "https://elliothe.github.io"

institution: Shanghai Jiao Tong University
department: Department of Computer Science and Engineering



include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
  math_engine: katex
  
# jekyii-scholar
scholar:
  last_name: He
  first_name: Zhezhi

  style: _bibliography/my_ieee.cls
  locale: en

  source: ./_bibliography
  bibliography: references.bib

  group_by: year
  group_order: descending

  replace_strings: true
  join_strings: true

  bibliography_template: bibliography

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*" 

  type_order: [article, inproceedings]

  
# Plugins
plugins:
  - jemoji
  - jekyll-sitemap
